; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = board1

[env:default]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
# Huge APP (3MB No OTA/1MB SPIFFS) is:
#   Name,   Type, SubType, Offset,  Size, Flags
#   nvs,      data, nvs,     0x9000,  0x5000,
#   otadata,  data, ota,     0xe000,  0x2000,
#   app0,     app,  ota_0,   0x10000, 0x300000,
#   spiffs,   data, spiffs,  0x310000,0xE0000,
#   coredump, data, coredump,0x3F0000,0x10000,
board_build.partitions = huge_app.csv
board_upload.maximum_size = 3145728
extra_scripts = pre:scripts/git_version.py
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    bblanchon/ArduinoJson @ ^7.3.1
    tzapu/WiFiManager @ ^2.0.17
    olikraus/U8g2 @ ^2.35.30

[env:esp32c3]
# GPIO 2, 8 and 9 should be avoided
extends = env:default
board = nologo_esp32c3_super_mini   

[env:board1]
extends = env:esp32c3
build_flags =
    ${env:default.build_flags}
    -DPIN_WIFI_RESET=10
    -DPIN_OLED_SCL=6
    -DPIN_OLED_SDA=5
    ; -DPIN_OLED_RESET=...
