; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:default]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = nologo_esp32c3_super_mini
framework = arduino
monitor_speed = 115200
upload_port = COM13
board_build.filesystem = littlefs
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    bblanchon/ArduinoJson @ ^7.3.1
    tzapu/WiFiManager @ ^2.0.17
    olikraus/U8g2 @ ^2.35.30
